//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3053.
// 
namespace sdMIRLA.WsSinapse {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsEstarSoap", Namespace="http://www.sinapseinformatica.com.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClasseBase))]
    public partial class WsEstar : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WsEstar() {
            this.Url = "http://192.168.0.189/WsSinapse/WsEstar.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sinapseinformatica.com.br/StringConexao", RequestNamespace="http://www.sinapseinformatica.com.br/", ResponseNamespace="http://www.sinapseinformatica.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StringConexao(string senha_master) {
            object[] results = this.Invoke("StringConexao", new object[] {
                        senha_master});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStringConexao(string senha_master, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StringConexao", new object[] {
                        senha_master}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStringConexao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sinapseinformatica.com.br/Sobre", RequestNamespace="http://www.sinapseinformatica.com.br/", ResponseNamespace="http://www.sinapseinformatica.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Sobre() {
            object[] results = this.Invoke("Sobre", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSobre(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Sobre", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSobre(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sinapseinformatica.com.br/RegistroAniel", RequestNamespace="http://www.sinapseinformatica.com.br/", ResponseNamespace="http://www.sinapseinformatica.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HistAtualizReg RegistroAniel(string senha_master, int id_licenca_cliente) {
            object[] results = this.Invoke("RegistroAniel", new object[] {
                        senha_master,
                        id_licenca_cliente});
            return ((HistAtualizReg)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegistroAniel(string senha_master, int id_licenca_cliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegistroAniel", new object[] {
                        senha_master,
                        id_licenca_cliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public HistAtualizReg EndRegistroAniel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HistAtualizReg)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sinapseinformatica.com.br/AtualizHistRegAniel", RequestNamespace="http://www.sinapseinformatica.com.br/", ResponseNamespace="http://www.sinapseinformatica.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AtualizHistRegAniel(string senha_master, int id_atualiz_reg, string usuario_aniel) {
            object[] results = this.Invoke("AtualizHistRegAniel", new object[] {
                        senha_master,
                        id_atualiz_reg,
                        usuario_aniel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAtualizHistRegAniel(string senha_master, int id_atualiz_reg, string usuario_aniel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AtualizHistRegAniel", new object[] {
                        senha_master,
                        id_atualiz_reg,
                        usuario_aniel}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAtualizHistRegAniel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sinapseinformatica.com.br/Cons_Equipe", RequestNamespace="http://www.sinapseinformatica.com.br/", ResponseNamespace="http://www.sinapseinformatica.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Equipe Cons_Equipe(string senha_master, string Cod_Equipe) {
            object[] results = this.Invoke("Cons_Equipe", new object[] {
                        senha_master,
                        Cod_Equipe});
            return ((Equipe)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCons_Equipe(string senha_master, string Cod_Equipe, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Cons_Equipe", new object[] {
                        senha_master,
                        Cod_Equipe}, callback, asyncState);
        }
        
        /// <remarks/>
        public Equipe EndCons_Equipe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Equipe)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sinapseinformatica.com.br/Cons_Produto", RequestNamespace="http://www.sinapseinformatica.com.br/", ResponseNamespace="http://www.sinapseinformatica.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Produto Cons_Produto(string senha_master, string Codmat) {
            object[] results = this.Invoke("Cons_Produto", new object[] {
                        senha_master,
                        Codmat});
            return ((Produto)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCons_Produto(string senha_master, string Codmat, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Cons_Produto", new object[] {
                        senha_master,
                        Codmat}, callback, asyncState);
        }
        
        /// <remarks/>
        public Produto EndCons_Produto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Produto)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public partial class HistAtualizReg : ClasseBase {
        
        private int idField;
        
        private Licenca_cliente licenca_clienteField;
        
        private System.DateTime data_envioField;
        
        private int qtde_licencaField;
        
        private System.DateTime liberado_ateField;
        
        private string versao_anielField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Licenca_cliente Licenca_cliente {
            get {
                return this.licenca_clienteField;
            }
            set {
                this.licenca_clienteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data_envio {
            get {
                return this.data_envioField;
            }
            set {
                this.data_envioField = value;
            }
        }
        
        /// <remarks/>
        public int Qtde_licenca {
            get {
                return this.qtde_licencaField;
            }
            set {
                this.qtde_licencaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Liberado_ate {
            get {
                return this.liberado_ateField;
            }
            set {
                this.liberado_ateField = value;
            }
        }
        
        /// <remarks/>
        public string Versao_aniel {
            get {
                return this.versao_anielField;
            }
            set {
                this.versao_anielField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public partial class Licenca_cliente : ClasseBase {
        
        private int idField;
        
        private Cliente clienteField;
        
        private System.DateTime data_vendaField;
        
        private System.DateTime inicio_suporteField;
        
        private System.DateTime data_criacao_bdField;
        
        private int situacaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data_venda {
            get {
                return this.data_vendaField;
            }
            set {
                this.data_vendaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Inicio_suporte {
            get {
                return this.inicio_suporteField;
            }
            set {
                this.inicio_suporteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data_criacao_bd {
            get {
                return this.data_criacao_bdField;
            }
            set {
                this.data_criacao_bdField = value;
            }
        }
        
        /// <remarks/>
        public int Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public partial class Cliente : ClasseBase {
        
        private int cod_clienteField;
        
        private string fantasiaField;
        
        private string razao_socialField;
        
        private int situacaoField;
        
        /// <remarks/>
        public int Cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                this.cod_clienteField = value;
            }
        }
        
        /// <remarks/>
        public string Fantasia {
            get {
                return this.fantasiaField;
            }
            set {
                this.fantasiaField = value;
            }
        }
        
        /// <remarks/>
        public string Razao_social {
            get {
                return this.razao_socialField;
            }
            set {
                this.razao_socialField = value;
            }
        }
        
        /// <remarks/>
        public int Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Produto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Perfil_Equipe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Licenca_cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HistAtualizReg))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public abstract partial class ClasseBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public partial class Produto : ClasseBase {
        
        private string codmatField;
        
        private string descricaoField;
        
        private string unidField;
        
        /// <remarks/>
        public string Codmat {
            get {
                return this.codmatField;
            }
            set {
                this.codmatField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Unid {
            get {
                return this.unidField;
            }
            set {
                this.unidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public partial class Perfil_Equipe : ClasseBase {
        
        private int cod_Perfil_EquipeField;
        
        private string nomeField;
        
        /// <remarks/>
        public int Cod_Perfil_Equipe {
            get {
                return this.cod_Perfil_EquipeField;
            }
            set {
                this.cod_Perfil_EquipeField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sinapseinformatica.com.br/")]
    public partial class Equipe : ClasseBase {
        
        private string cod_EquipeField;
        
        private string nomeField;
        
        private Perfil_Equipe perfilField;
        
        /// <remarks/>
        public string Cod_Equipe {
            get {
                return this.cod_EquipeField;
            }
            set {
                this.cod_EquipeField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public Perfil_Equipe Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
            }
        }
    }
}
